name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          # 添加其他需要的环境变量
          VITE_APP_TITLE: ${{ secrets.VITE_APP_TITLE }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Backup and clean server files
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "mkdir -p ${{ secrets.SERVER_PATH }}_backup_$TIMESTAMP"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cp -r ${{ secrets.SERVER_PATH }}/* ${{ secrets.SERVER_PATH }}_backup_$TIMESTAMP/ 2>/dev/null || true"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "rm -rf ${{ secrets.SERVER_PATH }}/*"

      - name: Upload files to server
        run: |
          rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no" \
            dist/* \
            nginx.conf \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PATH }}/

      - name: Configure Nginx
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "sudo cp ${{ secrets.SERVER_PATH }}/nginx.conf /etc/nginx/conf.d/park-check.conf && \
          sudo ln -sf /etc/nginx/conf.d/park-check.conf /etc/nginx/sites-enabled/park-check.conf && \
          sudo nginx -t && \
          sudo systemctl reload nginx"
